apiVersion: v1
kind: Service
metadata:
  name: ktrail-api
  labels:
    app: ktrail-api
    app.kubernetes.io/name: ktrail-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: ktrail-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
