apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: main
    path: charts/kube-prometheus-stack
    helm:
      valueFiles:
        - $values/monitoring/kube-prometheus-values.yaml
  sources:
    - repoURL: https://github.com/prometheus-community/helm-charts.git
      targetRevision: main
      path: charts/kube-prometheus-stack
      helm:
        valueFiles:
          - $values/monitoring/kube-prometheus-values.yaml
    - repoURL: https://github.com/chaudharyvineet/ktrail-git-ops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
